export const button_add_to_cart = "(//div[@class='pricebar']//button)[1]"
export const button_add_to_cart_2 = "(//div[@class='pricebar']//button)[2]"
export const shopping_cart_container = "//div[@id='shopping_cart_container']"
export const button_remove = "(//button[@id='remove-sauce-labs-backpack'])"
export const item_name = "(//div[@class='cart_item']//div[@class='cart_item_label'])[1]//a"
export const button_remove_detail = "(//button[normalize-space()='Remove'])[1]"
export const back_to_list_product = "(//button[@id='back-to-products'])"
export const checkout = "(//button[@id='checkout'])"
export const firstName = "(//input[@placeholder='First Name'])"
export const lastName = "(//input[@placeholder='Last Name'])"
export const postalCode = "(//input[@placeholder='Zip/Postal Code'])"
export const button_continue = "(//input[@id='continue'])"
export const button_finish = "(//button[@id='finish'])"
export const cartItems = "(//div[@class='cart_item'])"
export const itemPrices = "(//div[@class='cart_item']//div[@class='inventory_item_price'])"